### PR TITLE
Mathilde PR

### PR DESCRIPTION
**Pull request by mathildemalin**

### CODE REVIEW

**Comment by LTeinturier** [comment]
Outstanding work ! Please merge this asap !

**Comment by LTeinturier** [comment]
Finally it's not that good, improve it before I agree to the merge

**Comment by mathildemalin** [comment]
I'll ask Pauline !

**Review by LTeinturier — APPROVED** [review]

**Review by ivalaginja — APPROVED** [review]
This is good to go!

**Pull request merged**
